# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fj-8Otb8Xrxi9bntwpJqnPlnuggwF2XA
"""

import random


ranks = [_ for _ in range(2, 11)] + list('JQKA')
suits = 'spades diamonds clubs hearts'.split()

# Build deck
def build_deck():
    deck = [{'rank': r, 'suit': s} for r in ranks for s in suits]
    random.shuffle(deck)
    return deck


def card_wins(card1, card2):
    rank1 = ranks.index(card1['rank'])
    rank2 = ranks.index(card2['rank'])
    if rank1 > rank2:
        return card1
    elif rank2 > rank1:
        return card2
    else:
        return "It's a tie!"

def play_war():
    deck = build_deck()
    player1 = []
    player2 = []
    while len(deck) > 1:
        card1 = deck.pop()
        card2 = deck.pop()
        player1.append(card1)
        player2.append(card2)
        print(f"Player 1 drew: {card1['rank']} of {card1['suit']}")
        print(f"Player 2 drew: {card2['rank']} of {card2['suit']}")


        winner = card_wins(card1, card2)
        if winner == card1:
            print("Player 1 wins this round!")
            player1.extend([card1, card2])
        elif winner == card2:
            print("Player 2 wins this round!")
            player2.extend([card1, card2])
        else:
            print("It's a tie! Going to war...")


    if len(player1) > len(player2):
        print("Player 1 wins the game!")
    elif len(player2) > len(player1):
        print("Player 2 wins the game!")
    else:
        print("It's a tie game!")

play_war()